### ISSUE TITLE
Make requests cancelable

### ISSUE THREAD

**Issue by EmileTrotignon** [art-w/sherlodoc#36]
When you use sherlodoc as a website, requests are made for each letter you type. But if a request is slow enough that it is not answered by the time another request arrives, it would be ideal to cancel it.

Lwt is not suitable for this kind of thing, because we do not want to link the performance critical code with Lwt, because that would make the js file size too big.

This means that we need to do that with system threads. System thread have interruption points injected by the OCaml runtime, so this should work nicely. 

Fabrice kindly provided me with a short demo of interruption with system threads : 
```ocaml
exception Interrupt_Me

let work () =
  let i = ref 0 in
  while true; do
    Printf.printf "I'm still here (%d)...\n%!" !i;
    Unix.sleep 1;
    i := !i + 1;
  done

let install_sighandler () =
  let signum = Sys.sigint in
  Printf.printf "Installing signal handler for %d\n%!" signum;
  let _ = Sys.set_signal signum (Sys.Signal_handle (fun _ ->
    Printf.printf "Signal received! Raising excpetion...\n%!";
    raise Interrupt_Me))
  in
  ()

let interruptable f =
  install_sighandler ();
  Printf.printf "Hello, my pid is %d, interrupt me!\n%!" (Unix.getpid ());
  try f () with
  | Interrupt_Me -> Printf.printf "Exception caught... aborting life\n%!"
  | _ -> assert false

let () =
  Printf.printf "Hello world\n%!";
  interruptable work;
  Printf.printf "Goodbye world\n%!"
```

**Comment by art-w** [comment]
As discussed with Emile, I'm not sure about this one:
- The webserver already runs queries inside Lwt to support concurrent requests (so we should not need threads to make queries cancelable), with some magic to avoid bundling Lwt in the jsoo version
- Requests are not cancelled by the js client (so the webserver doesn't know that it should cancel the query!)
- Requests are however cached by the web browser: When hitting the backspace key following a typo, the user gets instant results from the cache because we didn't cancel their intermediate queries.

I kinda like this caching that we get for free right now, so I'm not sure this issue is worth the effort (but a timeout on query execution #37 would be nice).
